/** Minimal Registry ABI for read-only protocol / pitch alignment. */
export const registryAbi = [
  {
    type: "function",
    name: "BPS_DENOMINATOR",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BPS_COMPETITORS_WITH_TRIAGE",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BPS_JUDGES_WITH_TRIAGE",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BPS_TRIAGE_WITH_TRIAGE",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BPS_TREASURY_WITH_TRIAGE",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BPS_COMPETITORS_NO_TRIAGE",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BPS_JUDGES_NO_TRIAGE",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BPS_TREASURY_NO_TRIAGE",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PUNISH_PARTICIPANT_BPS",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sponsorNFT",
    inputs: [],
    outputs: [{ type: "address", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "triageNFT",
    inputs: [],
    outputs: [{ type: "address", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "competitorNFT",
    inputs: [],
    outputs: [{ type: "address", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolTreasury",
    inputs: [],
    outputs: [{ type: "address", name: "" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ctfCreationTime",
    inputs: [{ name: "ctfId", type: "uint256" }],
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "CtfCreated",
    inputs: [
      { name: "ctfId", type: "uint256", indexed: true },
      { name: "creationTime", type: "uint256", indexed: false },
      { name: "supportsTriage", type: "bool", indexed: false },
      { name: "sponsor", type: "address", indexed: false },
    ],
  },
] as const
